# Generated by Django 2.2.1 on 2019-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_addasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=50)),
                ('DocumentSequence', models.CharField(max_length=50)),
                ('DocumentNumber', models.CharField(max_length=50)),
                ('DocumentName', models.CharField(max_length=50)),
                ('Attachment', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectNumber', models.CharField(max_length=50)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectContact', models.CharField(max_length=50)),
                ('ProjectAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
