# Generated by Django 2.2.1 on 2019-05-04 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_addprojectdocument_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTechDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=50)),
                ('DocumentSequence', models.CharField(max_length=50)),
                ('DocumentNumber', models.CharField(max_length=50)),
                ('DocumentName', models.CharField(max_length=50)),
                ('Attachment', models.FileField(upload_to='documents/')),
                ('IssueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetCorrespondance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetNumber', models.CharField(max_length=50)),
                ('UserGuide', models.CharField(max_length=50)),
                ('WarrentyCard', models.CharField(max_length=50)),
                ('BillNumber', models.CharField(max_length=50)),
                ('PaymentMode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetNumber', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Specifications', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetNumber', models.CharField(max_length=50)),
                ('DueDate', models.DateField()),
                ('Payment', models.CharField(max_length=50)),
                ('EnterAmt', models.CharField(max_length=50)),
                ('RemBal', models.CharField(max_length=50)),
                ('PaymentRecpt', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('CashRecived', models.CharField(max_length=50)),
                ('Paid', models.CharField(max_length=50)),
                ('Amount', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=50)),
                ('InvestmentNum', models.CharField(max_length=50)),
                ('DocumentNumber', models.CharField(max_length=50)),
                ('DocumentName', models.CharField(max_length=50)),
                ('DueDate', models.DateField()),
                ('Attachment', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=50)),
                ('DocumentSequence', models.CharField(max_length=50)),
                ('DocumentNumber', models.CharField(max_length=50)),
                ('DocumentName', models.CharField(max_length=50)),
                ('IssueDate', models.DateField()),
                ('Attachment', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ReferanceDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=50)),
                ('DocumentSequence', models.CharField(max_length=50)),
                ('DocumentNumber', models.CharField(max_length=50)),
                ('DocumentName', models.CharField(max_length=50)),
                ('IssueDate', models.DateField()),
                ('Attachment', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='WarrentyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetNum', models.CharField(max_length=50)),
                ('WarrentyStart', models.DateField()),
                ('ServiceAddrs', models.CharField(max_length=50)),
                ('ServiceCentre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='addprojectdocument',
            name='IssueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
